# Generated by Django 4.2.5 on 2024-02-15 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("notification", "0003_notification")]

    operations = [migrations.DeleteModel(name="UserNotification")]
