version: '3.8'

services:
  db:
    image: 'postgres:12'
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db-env
    ports:
      - '5433:5432'
    networks:
      - fele-network

  redis:
    image: 'redis:5'
    hostname: redis
    volumes:
      - redis_data:/data/
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    networks:
      - fele-network
    restart: "always"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    networks:
      - fele-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A feleexpress worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    networks:
      - fele-network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        'celery',
        '--app=feleexpress',
        'beat',
        '--scheduler=django_celery_beat.schedulers:DatabaseScheduler',
        '--loglevel=INFO',
      ]
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    networks:
      - fele-network

volumes:
  postgres_data:
  redis_data:

networks:
  fele-network:
