version: '3.8'

services:
  db:
    image: 'postgres:12'
    hostname: postgres
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data/
    env_file:
      - ./.db-env
    ports:
      - '5434:5432'
    networks:
      - fele-staging-network

  redis:
    image: 'redis:5'
    hostname: redis
    volumes:
      - redis_staging_data:/data/
    ports:
      - '6380:6379'
    networks:
      - fele-staging-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    networks:
      - fele-staging-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A feleexpress worker --loglevel=info
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    networks:
      - fele-staging-network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      [
        'celery',
        '--app=feleexpress',
        'beat',
        '--scheduler=django_celery_beat.schedulers:DatabaseScheduler',
        '--loglevel=INFO',
      ]
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    networks:
      - fele-staging-network

volumes:
  postgres_staging_data:
  redis_staging_data:

networks:
  fele-staging-network:
