version: '3.8'

services:
  db:
    image: 'postgres:12'
    hostname: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db-env
    ports:
      - '5433:5432'
    networks:
      - fele-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - fele-network

volumes:
  postgres_data:

networks:
  fele-network:
