# Generated by Django 4.2.5 on 2023-11-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("customer", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="business_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="business_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="business_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="delivery_volume",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
