# Generated by Django 4.2.5 on 2023-11-22 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "customer",
            "0002_customer_business_address_customer_business_category_and_more",
        )
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCustomer",
            fields=[],
            options={
                "verbose_name": "Customer (Business)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("customer.customer",),
        ),
        migrations.CreateModel(
            name="IndividualCustomer",
            fields=[],
            options={
                "verbose_name": "Customer (Individual)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("customer.customer",),
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "customer", "verbose_name_plural": "customers"},
        ),
        migrations.AlterModelTable(name="customer", table="customer"),
    ]
