# Generated by Django 4.2.5 on 2024-01-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("notification", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="meta_data",
            field=models.JSONField(
                default=dict, null=True, verbose_name="User notification context"
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="notification_type",
            field=models.CharField(
                choices=[("SMS", "SMS"), ("PUSH", "PUSH")],
                default="PUSH",
                verbose_name="notification type",
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                default="ACTIVE",
                verbose_name="notification status",
            ),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="subscription_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="subscription id"
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="external id"
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="one_signal_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="one_signal id"
            ),
        ),
    ]
