# Generated by Django 4.2.5 on 2024-02-15 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_notification_thirdpartynotification_and_more")
    ]

    operations = [
        migrations.RemoveField(model_name="thirdpartynotification", name="created_by"),
        migrations.RemoveField(model_name="thirdpartynotification", name="deleted_by"),
        migrations.RemoveField(model_name="thirdpartynotification", name="updated_by"),
        migrations.RemoveField(model_name="thirdpartynotification", name="user"),
        migrations.DeleteModel(name="Notification"),
        migrations.DeleteModel(name="ThirdPartyNotification"),
    ]
