# Generated by Django 4.2.5 on 2023-09-30 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import helpers.db_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.db_helpers.generate_id,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BICYCLE", "BICYCLE"),
                            ("MOTORCYCLE", "MOTORCYCLE"),
                            ("CAR", "CAR (SEDAN)"),
                            ("MPV", "MPV (MULTI-PURPOSE VAN)"),
                            ("TRUCKS", "TRUCKS"),
                        ],
                        max_length=30,
                        verbose_name="rider's vehicle type",
                    ),
                ),
                ("rider_info", models.TextField(blank=True, null=True)),
                (
                    "avatar_url",
                    models.CharField(
                        blank=True, max_length=550, null=True, verbose_name="avatar url"
                    ),
                ),
                ("vehicle_photos", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "APPROVED"),
                            ("UNAPPROVED", "UNAPPROVED"),
                            ("SUSPENDED", "SUSPENDED"),
                        ],
                        default="UNAPPROVED",
                        max_length=30,
                        verbose_name="Rider workspace status",
                    ),
                ),
                (
                    "status_updates",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "operation_locations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Locations where rider operate in Nigeria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "rider",
                "verbose_name_plural": "rider",
                "db_table": "rider",
            },
        ),
        migrations.CreateModel(
            name="VerificationId",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.db_helpers.generate_id,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "Government Issued Identification",
                                "Government Issued Identification",
                            ),
                            ("Vehicle Registration", "Vehicle Registration"),
                            ("Utility Bill", "Utility Bill"),
                            (
                                "National Identification Number",
                                "National Identification Number",
                            ),
                            ("Drivers License", "Drivers License"),
                        ],
                        max_length=100,
                        verbose_name="identification type",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="identification number",
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True,
                        max_length=550,
                        null=True,
                        verbose_name="identification file url",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rider.rider"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Id",
                "verbose_name_plural": "Verification Ids",
                "db_table": "verification_id",
            },
        ),
        migrations.CreateModel(
            name="RiderRating",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.db_helpers.generate_id,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_rating",
                        to="customer.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_rating",
                        to="rider.rider",
                        verbose_name="rider",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider Rating",
                "verbose_name_plural": "Rider Ratings",
                "db_table": "rider_rating",
            },
        ),
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.db_helpers.generate_id,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=350, verbose_name="full name"),
                ),
                ("address", models.CharField(max_length=550, verbose_name="address")),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="phone number"),
                ),
                (
                    "relationship",
                    models.CharField(
                        max_length=100, verbose_name="relationship with the provider"
                    ),
                ),
                (
                    "contact_mode",
                    models.CharField(
                        max_length=100,
                        verbose_name="best mode to contact the reference",
                    ),
                ),
                (
                    "guarantor_letter",
                    models.CharField(max_length=550, verbose_name="address"),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, verbose_name="Is reference verified?"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rider.rider"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "guarantor",
                "verbose_name_plural": "guarantor",
                "db_table": "guarantor",
            },
        ),
    ]
