# Generated by Django 4.2.5 on 2023-09-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rider", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rider",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("BICYCLE", "BICYCLE"),
                    ("CAR", "CAR (SEDAN)"),
                    ("KEKE", "KEKE"),
                    ("MOTORCYCLE", "MOTORCYCLE"),
                    ("MPV", "MPV (MULTI-PURPOSE VAN)"),
                    ("TRUCKS", "TRUCKS"),
                ],
                max_length=30,
                verbose_name="rider's vehicle type",
            ),
        ),
    ]
