# Generated by Django 4.2.5 on 2023-10-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0002_rider_city_alter_rider_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="vehicle_color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="vehicle_make",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="vehicle_plate_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
