# Generated by Django 4.2.5 on 2023-10-08 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import helpers.db_helpers


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rider", "0003_rider_vehicle_color_rider_vehicle_make_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderDocument",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.db_helpers.generate_id,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Vehicle Registration", "Vehicle Registration"),
                            ("driver_license", "Driver License"),
                            ("vehicle_photo", "Vehicle Photo"),
                            ("passport_photo", "Passport Photo"),
                            ("government_id", "government Issued Identification"),
                            ("guarantor_letter", "Guarantor Letter"),
                            (
                                "address_verification",
                                "Address Verification (Utility Bill)",
                            ),
                        ],
                        max_length=100,
                        verbose_name="document type",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="document number",
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True,
                        max_length=550,
                        null=True,
                        verbose_name="document file url",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider Document",
                "verbose_name_plural": "Rider Documents",
                "db_table": "rider_document",
            },
        ),
        migrations.AlterField(
            model_name="rider",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BICYCLE", "BICYCLE"),
                    ("CAR", "CAR (SEDAN)"),
                    ("KEKE", "KEKE"),
                    ("MOTORCYCLE", "MOTORCYCLE"),
                    ("MPV", "MPV (MULTI-PURPOSE VAN)"),
                    ("TRUCKS", "TRUCKS"),
                ],
                max_length=30,
                null=True,
                verbose_name="rider's vehicle type",
            ),
        ),
        migrations.DeleteModel(name="VerificationId"),
        migrations.AddField(
            model_name="riderdocument",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rider.rider"
            ),
        ),
        migrations.AddField(
            model_name="riderdocument",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
    ]
