# Generated by Django 4.2.5 on 2023-10-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("rider", "0004_riderdocument_alter_rider_vehicle_type_and_more")]

    operations = [
        migrations.AlterField(
            model_name="riderdocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("vehicle_registration", "Vehicle Registration"),
                    ("driver_license", "Driver License"),
                    ("vehicle_photo", "Vehicle Photo"),
                    ("passport_photo", "Passport Photo"),
                    ("government_id", "government Issued Identification"),
                    ("guarantor_letter", "Guarantor Letter"),
                    ("address_verification", "Address Verification (Utility Bill)"),
                ],
                max_length=100,
                verbose_name="document type",
            ),
        )
    ]
