# Generated by Django 4.2.5 on 2023-10-09 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("rider", "0005_alter_riderdocument_type")]

    operations = [migrations.RemoveField(model_name="rider", name="vehicle_photos")]
