# Generated by Django 4.2.5 on 2023-11-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("rider", "0006_remove_rider_vehicle_photos")]

    operations = [
        migrations.AlterField(
            model_name="riderdocument",
            name="rider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rider_document",
                to="rider.rider",
                verbose_name="rider",
            ),
        ),
        migrations.AlterField(
            model_name="riderdocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("address_verification", "Address Verification (Utility Bill)"),
                    ("driver_license", "Driver License"),
                    ("insurance_certificate", "Insurance Certificate"),
                    ("government_id", "Government Issued Identification"),
                    ("guarantor_letter", "Guarantor Letter"),
                    ("passport_photo", "Passport Photo"),
                    ("vehicle_registration", "Vehicle Registration"),
                    ("vehicle_photo", "Vehicle Photo"),
                ],
                max_length=100,
                verbose_name="document type",
            ),
        ),
        migrations.AlterField(
            model_name="riderdocument",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
    ]
