# Generated by Django 4.2.5 on 2023-11-22 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rider", "0007_alter_riderdocument_rider_alter_riderdocument_type_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedRider",
            fields=[],
            options={
                "verbose_name": "Rider (Approved)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("rider.rider",),
        ),
        migrations.CreateModel(
            name="UnApprovedRider",
            fields=[],
            options={
                "verbose_name": "Rider (Unapproved)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("rider.rider",),
        ),
    ]
