# Generated by Django 4.2.5 on 2024-01-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("rider", "0009_rider_vehicle_alter_rider_vehicle_type")]

    operations = [
        migrations.AlterField(
            model_name="riderdocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("address_verification", "Address Verification (Utility Bill)"),
                    ("driver_license", "Driver License"),
                    ("insurance_certificate", "Insurance Certificate"),
                    ("government_id", "Government Issued Identification"),
                    ("guarantor_letter", "Guarantor Letter"),
                    ("passport_photo", "Passport Photo"),
                    ("vehicle_registration", "Vehicle Registration"),
                    ("vehicle_photo", "Vehicle Photo"),
                    (
                        "certificate_of_vehicle_registration",
                        "Certificate Of Vehicle Registration",
                    ),
                    ("authorization_letter", "Authorization Letter"),
                ],
                max_length=100,
                verbose_name="document type",
            ),
        )
    ]
