# Generated by Django 4.2.5 on 2024-02-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("rider", "0012_favoriterider")]

    operations = [
        migrations.AddField(
            model_name="rider", name="on_duty", field=models.BooleanField(default=False)
        )
    ]
