# Generated by Django 4.2.5 on 2023-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("authentication", "0003_user_is_deactivated")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_email_promotions",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user will receive newsletter and all.",
                verbose_name="Did user signup for promotion",
            ),
        )
    ]
