# Generated by Django 4.2.5 on 2023-11-05 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("wallet", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="wallet", name="created_by"),
        migrations.RemoveField(model_name="wallet", name="deleted_by"),
        migrations.RemoveField(model_name="wallet", name="updated_by"),
        migrations.RemoveField(model_name="wallet", name="user"),
        migrations.DeleteModel(name="Transaction"),
        migrations.DeleteModel(name="Wallet"),
    ]
