# Generated by Django 4.2.5 on 2023-11-05 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import helpers.db_helpers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0002_remove_wallet_created_by_remove_wallet_deleted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.db_helpers.generate_id,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=helpers.db_helpers.generate_id,
                        editable=False,
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("DELETED", "DELETED")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CREDIT", "CREDIT"), ("DEBIT", "DEBIT")],
                        default="CREDIT",
                        max_length=255,
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                            ("REVERSED", "REVERSED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="PENDING",
                        max_length=255,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "currency",
                    models.CharField(
                        choices=[("NGN", "₦")],
                        default="₦",
                        max_length=30,
                        verbose_name="transaction currency",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "pssp",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "PAYSTACK"),
                            ("IN_HOUSE", "IN HOUSE TRANSACTION"),
                        ],
                        default="PAYSTACK",
                        max_length=255,
                    ),
                ),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("wallet_id", models.CharField(blank=True, max_length=255, null=True)),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "object_class",
                    models.CharField(
                        blank=True,
                        choices=[("USER", "USER"), ("RIDER", "RIDER")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "payment_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FUND_WALLET", "Funds wallet"),
                            ("USER_PAY_RIDER", "User pays rider"),
                            ("RIDER_PAY_USER", "Rider pays user"),
                            ("WITHDRAW", "Withdrawal"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "pssp_meta_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_payee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_payor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transaction",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
