# Generated by Django 4.2.5 on 2023-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("wallet", "0003_initial")]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="object_class",
            field=models.CharField(
                blank=True,
                choices=[("CUSTOMER", "CUSTOMER"), ("RIDER", "RIDER")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FUND_WALLET", "Funds wallet"),
                    ("CUSTOMER_PAY_RIDER", "Customer pays rider"),
                    ("RIDER_PAY_CUSTOMER", "Rider pays customer"),
                    ("WITHDRAW", "Withdrawal"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
