# Generated by Django 4.2.5 on 2023-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("wallet", "0006_alter_card_options_alter_card_table_bankaccount")]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="save_account",
            field=models.BooleanField(default=False),
        )
    ]
