# Generated by Django 4.2.5 on 2024-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("wallet", "0009_alter_transaction_user")]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="recipient_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
