# Generated by Django 4.2.5 on 2024-03-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("business", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="business",
            name="e_secret_key",
            field=models.CharField(blank=True, max_length=700, null=True),
        )
    ]
