# Generated by Django 4.2.5 on 2023-11-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="vehicles",
            options={
                "verbose_name": "Available Vehicle",
                "verbose_name_plural": "Available Vehicles",
            },
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Active period end date",
            ),
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="name",
            field=models.CharField(max_length=50, verbose_name="vehicle name"),
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Active period start date",
            ),
        ),
    ]
