# Generated by Django 4.2.5 on 2023-11-22 20:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0002_alter_vehicles_options_alter_vehicles_end_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Vehicles", new_name="Vehicle"),
        migrations.RenameField(
            model_name="vehicle", old_name="km_10_fare", new_name="km_5_above_fare"
        ),
        migrations.RenameField(
            model_name="vehicle", old_name="km_5_fare", new_name="km_5_below_fare"
        ),
    ]
