# Generated by Django 4.2.5 on 2023-11-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0003_rename_vehicles_vehicle_and_more")]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="note",
            field=models.CharField(
                blank=True, max_length=550, null=True, verbose_name="vehicle note"
            ),
        )
    ]
