# Generated by Django 4.2.5 on 2023-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0004_vehicle_note")]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="file_url",
            field=models.CharField(
                blank=True, max_length=550, null=True, verbose_name="Vehicle image url"
            ),
        )
    ]
