# Generated by Django 4.2.5 on 2024-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0007_alter_order_chat_id")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="distance",
            field=models.CharField(help_text="represented in meters", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_stop_overs_meta_data",
            field=models.JSONField(default=list, help_text="Stop overs information"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_timeline",
            field=models.JSONField(default=list, help_text="Ordered timeline tracking"),
        ),
    ]
