# Generated by Django 4.2.5 on 2024-02-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0008_alter_order_distance_and_more")]

    operations = [
        migrations.AddField(
            model_name="order", name="paid", field=models.BooleanField(default=False)
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING_ORDER", "Processing"),
                    ("RIDER_ACCEPTED_ORDER", "Rider accepted order"),
                    ("RIDER_AT_PICK_UP", "Rider at pick up"),
                    ("RIDER_PICKED_UP_ORDER", "Rider picked up order"),
                    ("ORDER_ARRIVED", "Order arrived"),
                    ("ORDER_DELIVERED", "Order delivered"),
                    ("ORDER_COMPLETED", "Order completed"),
                    ("ORDER_CANCELLED", "Order cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
