# Generated by Django 4.2.5 on 2024-02-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0010_order_fele_amount_order_paid_fele")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING_ORDER", "Processing"),
                    ("PENDING_RIDER_CONFIRMATION", "Awaiting rider confirmation"),
                    ("RIDER_ACCEPTED_ORDER", "Rider accepted order"),
                    ("RIDER_AT_PICK_UP", "Rider at pick up"),
                    ("RIDER_PICKED_UP_ORDER", "Rider picked up order"),
                    ("ORDER_ARRIVED", "Order arrived"),
                    ("ORDER_DELIVERED", "Order delivered"),
                    ("ORDER_COMPLETED", "Order completed"),
                    ("ORDER_CANCELLED", "Order cancelled"),
                ],
                default="PENDING",
                max_length=50,
            ),
        )
    ]
