# Generated by Django 4.2.5 on 2024-03-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("order", "0013_ordertimeline")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
