# Generated by Django 4.2.5 on 2024-03-20 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("order", "0014_order_delivery_name_order_pickup_name")]

    operations = [
        migrations.CreateModel(
            name="PendingOrder",
            fields=[],
            options={
                "verbose_name": "Orders (Awaiting rider)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("order.order",),
        )
    ]
