# Generated by Django 4.2.5 on 2024-03-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_business_e_secret_key"),
        ("customer", "0003_businesscustomer_individualcustomer_and_more"),
        ("order", "0015_pendingorder"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="order_timeline"),
        migrations.AddField(
            model_name="order",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_order",
                to="business.business",
                verbose_name="business",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_by",
            field=models.CharField(
                choices=[("CUSTOMER", "Customer"), ("BUSINESS", "Business")],
                default="CUSTOMER",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_order",
                to="customer.customer",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="ordertimeline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_timeline",
                to="order.order",
                verbose_name="order_timeline",
            ),
        ),
    ]
