# Generated by Django 4.2.5 on 2024-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_remove_order_order_timeline_order_business_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                default="INACTIVE",
                max_length=30,
                verbose_name="status",
            ),
        )
    ]
